version: "2"
services:
  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    image: docker-registry.usersys.redhat.com/bayesian/coreapi-flower
    container_name: coreapi-flower
    network_mode: bridge
    ports:
     - "31000:5555"
    links:
     - broker
    environment:
      RABBITMQ_SERVICE_SERVICE_HOST: broker
  pgweb:
    build:
      context: .
      dockerfile: Dockerfile.pgweb
    image: docker-registry.usersys.redhat.com/bayesian/coreapi-pgweb:latest
    network_mode: bridge
    ports:
     - "31003:8080"
    links:
     - pgbouncer
    environment:
      DATABASE_URL: "postgres://coreapi:coreapi@coreapi-pgbouncer:5432/coreapi?sslmode=disable"
    restart: always
    container_name: coreapi-pgweb
