  
---
apiVersion: v1
kind: Template
metadata:
  name: f8a-e2e-tests
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: f8a-e2e-tests-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: ${IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: github-mirror-acceptance
            env:
              - name: GITHUB_MIRROR_URL
                value: ${GITHUB_MIRROR_URL}
              - name: CLIENT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: ${CLIENT_TOKEN_SECRET}
                    key: CLIENT_TOKEN
            command:
              - make
            args:
              - accept
parameters:
- name: IMAGE
  value: quay.io/app-sre/f8a-e2e-tests
- name: IMAGE_TAG
  value: 'latest'
  required: true
- name: GITHUB_MIRROR_URL
  value: ''
  required: true
- name: CLIENT_TOKEN_SECRET
  value: ''
  required: true