[[Bayesian API Fuzzer]]]
= Bayesian API Fuzzer (BAF)

The Bayesian API Fuzzer is used to check the behaviour of  REST API endpoints by sending invalid and unexpected data as the payload. The data is not completely random as they are generated by "mutating" payload that is known to be correct.

[[preliminary-info]]
== Preliminary info

From Wikipedia: "Fuzzing or fuzz testing is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program. The program is then monitored for exceptions such as crashes, failing built-in code assertions, or potential memory leaks."

[[setup]]
== Setup

You need to provide environment variables with URL to servers. Names of those variables are then used in the file `tests.csv` that contains test specification.

[[running]]
== Running BAF

 baf.py [-h] [-u URL] [-D] [-H] [-C]
 optional arguments:
   -h, --help            show this help message and exit
   -v, --version         show version information
   -i INPUT, --input INPUT
   -u URL, --url URL     specify URL to test
   -D, --dry             dry run (do not call REST API)
   -t TEXT, --text TEXT  generate report in plain text format
   -H HTML, --html HTML  generate report in HTML format
   -C CSV, --csv CSV     generate report in CSV format
   -T TSV, --tsv TSV     generate report in TSV format
   -X XML, --xml XML     generate report in XML format


[[Reports]]
== Reports

[[known-issues]]
== Known issues

[[TODO]]
== TODO

