Feature: Smoke tests for the component analysis REST API


  Scenario Outline: Check the component analysis REST API endpoint for 100 most popular PyPi components
    Given System is running
     When I acquire the authorization token
     Then I should get the proper authorization token

     When I read <ecosystem>/<package>/<version> component analysis with authorization token
     Then I should get 200 status code
      And I should receive a valid JSON response

     When I look at the component analysis duration
     Then I should see that the component analysis duration is less than 10 second

     When I look at recent component analysis
     Then I should receive JSON response containing the result key
      And I should find at least one analyzed package in the component analysis
      And I should find the package <package> from <ecosystem> ecosystem in the component analysis
      And I should find the component <package> version <version> from <ecosystem> ecosystem in the component analysis
      And I should find new recommended version in case the CVE is detected for an analyzed component
      And I should find CVE report in case the CVE is detected for an analyzed component

     Examples: EPV
     | ecosystem  | package             | version              |
     | pypi       | pip                 | 19.2.1               | #1
     | pypi       | urllib3             | 1.25.3               | #2
     | pypi       | botocore            | 1.12.202             | #3
     | pypi       | six                 | 1.12.0               | #4
     | pypi       | python-dateutil     | 2.8.0                | #5
     | pypi       | s3transfer          | 0.2.1                | #6
     | pypi       | pyyaml              | 5.1.2                | #7
     | pypi       | docutils            | 0.15.2               | #8
     | pypi       | pyasn1              | 0.4.6                | #9
     | pypi       | requests            | 2.22.0               | #10
     | pypi       | setuptools          | 41.0.1               | #11
     | pypi       | jmespath            | 0.9.4                | #12
     | pypi       | certifi             | 2019.6.16            | #13
     | pypi       | awscli              | 1.16.212             | #14
     | pypi       | rsa                 | 4.0                  | #15
     | pypi       | futures             | 3.3.0                | #16
     | pypi       | idna                | 2.8                  | #17
     | pypi       | colorama            | 0.4.1                | #18
     | pypi       | wheel               | 0.33.4               | #19
     | pypi       | chardet             | 3.0.4                | #20
     | pypi       | simplejson          | 3.16.0               | #21
     | pypi       | boto3               | 1.9.202              | #22
     | pypi       | pytz                | 2019.2               | #23
     | pypi       | numpy               | 1.17.0               | #24
     | pypi       | cffi                | 1.12.3               | #25
     | pypi       | markupsafe          | 1.1.1                | #26
     | pypi       | cryptography        | 2.7                  | #27
     | pypi       | awscli-cwlogs       | 1.4.5                | #28
     | pypi       | jinja2              | 2.10.1               | #29
     | pypi       | pycparser           | 2.19                 | #30
     | pypi       | pbr                 | 5.4.2                | #31
     | pypi       | enum34              | 1.1.6                | #32
     | pypi       | protobuf            | 3.9.1                | #33
     | pypi       | asn1crypto          | 0.24.0               | #34
     | pypi       | ipaddress           | 1.0.22               | #35
     | pypi       | click               | 7.0                  | #36
     | pypi       | pytest              | 5.0.1                | #37
     | pypi       | attrs               | 19.1.0               | #38
     | pypi       | future              | 0.17.1               | #39
     | pypi       | decorator           | 4.4.0                | #40
     | pypi       | pyparsing           | 2.4.2                | #41
     | pypi       | pandas              | 0.25.0               | #42
     | pypi       | pytest-runner       | 5.1                  | #43
     | pypi       | pyasn1-modules      | 0.2.6                | #44
     | pypi       | werkzeug            | 0.15.5               | #45
     | pypi       | psutil              | 5.6.3                | #46
     | pypi       | virtualenv          | 16.7.2               | #47
     | pypi       | flask               | 1.1.1                | #48
     | pypi       | boto                | 2.49.0               | #49
     | pypi       | py                  | 1.8.0                | #50
     | pypi       | itsdangerous        | 1.1.0                | #51
     | pypi       | google-api-core     | 1.14.2               | #52
     | pypi       | coverage            | 4.5.4                | #53
     | pypi       | argparse            | 1.4.0                | #54
     | pypi       | setuptools-scm      | 3.3.3                | #55
     | pypi       | pluggy              | 0.12.0               | #56
     | pypi       | mock                | 3.0.5                | #57
     | pypi       | scipy               | 1.3.0                | #58
     | pypi       | grpcio              | 1.22.0               | #59
     | pypi       | pyopenssl           | 19.0.0               | #60
     | pypi       | google-cloud-core   | 1.0.3                | #61
     | pypi       | pygments            | 2.4.2                | #62
     | pypi       | jsonschema          | 3.0.2                | #63
     | pypi       | psycopg2            | 2.8.3                | #64
     | pypi       | scikit-learn        | 0.21.3               | #65
     | pypi       | more-itertools      | 7.2.0                | #66
     | pypi       | cachetools          | 3.1.1                | #67
     | pypi       | pillow              | 6.1.0                | #68
     | pypi       | lxml                | 4.4.0                | #69
     | pypi       | docopt              | 0.6.2                | #70
     | pypi       | google-auth         | 1.6.3                | #71
     | pypi       | funcsigs            | 1.0.2                | #72
     | pypi       | websocket-client    | 0.56.0               | #73
     | pypi       | httplib2            | 0.13.1               | #74
     | pypi       | oauth2client        | 4.1.3                | #75
     | pypi       | google-api-python-client | 1.7.10               | #76
     | pypi       | mccabe              | 0.6.1                | #77
     | pypi       | paramiko            | 2.6.0                | #78
     | pypi       | tornado             | 6.0.3                | #79
     | pypi       | ptyprocess          | 0.6.0                | #80
     | pypi       | pyjwt               | 1.7.1                | #81
     | pypi       | pexpect             | 4.7.0                | #82
     | pypi       | sqlalchemy          | 1.3.6                | #83
     | pypi       | matplotlib          | 3.1.1                | #84
     | pypi       | uritemplate         | 3.0.0                | #85
     | pypi       | wrapt               | 1.11.2               | #86
     | pypi       | bcrypt              | 3.1.7                | #87
     | pypi       | pycodestyle         | 2.5.0                | #88
     | pypi       | markdown            | 3.1.1                | #89
     | pypi       | google-resumable-media | 0.3.2                | #90
     | pypi       | oauthlib            | 3.1.0                | #91
     | pypi       | elasticsearch       | 7.0.2                | #92
     | pypi       | docker              | 4.0.2                | #93
     | pypi       | ipython             | 7.7.0                | #94
     | pypi       | docker-pycreds      | 0.4.0                | #95
     | pypi       | prompt-toolkit      | 2.0.9                | #96
     | pypi       | atomicwrites        | 1.3.0                | #97
     | pypi       | multidict           | 4.5.2                | #98
     | pypi       | pymysql             | 0.9.3                | #99
     | pypi       | redis               | 3.3.6                | #100
     | pypi       | pynacl              | 1.3.0                | #101
     | pypi       | requests-oauthlib   | 1.2.0                | #102
     | pypi       | google-cloud-bigquery | 1.17.0               | #103
     | pypi       | absl-py             | 0.7.1                | #104
     | pypi       | aiohttp             | 3.5.4                | #105
     | pypi       | sklearn             | 0.0                  | #106
     | pypi       | pymemcache          | 2.2.2                | #107
     | pypi       | pyflakes            | 2.1.1                | #108
     | pypi       | beautifulsoup4      | 4.8.0                | #109
     | pypi       | packaging           | 19.1                 | #110
     | pypi       | google-cloud-storage | 1.18.0               | #111
     | pypi       | wcwidth             | 0.1.7                | #112
     | pypi       | nose                | 1.3.7                | #113
     | pypi       | configparser        | 3.7.4                | #114
     | pypi       | greenlet            | 0.4.15               | #116
     | pypi       | functools32         | 3.2.3-2              | #117
     | pypi       | gevent              | 1.4.0                | #118
     | pypi       | ujson               | 1.35                 | #119
     | pypi       | googleapis-common-protos | 1.6.0                | #120
     | pypi       | django              | 2.2.4                | #121
     | pypi       | gunicorn            | 19.9.0               | #122
     | pypi       | typing              | 3.7.4                | #123
     | pypi       | babel               | 2.7.0                | #124
     | pypi       | lazy-object-proxy   | 1.4.1                | #125
     | pypi       | ipython-genutils    | 0.2.0                | #126
     | pypi       | cython              | 0.29.13              | #127
     | pypi       | traitlets           | 4.3.2                | #128
     | pypi       | toolz               | 0.10.0               | #129
     | pypi       | flake8              | 3.7.8                | #130
     | pypi       | pathlib2            | 2.3.4                | #131
     | pypi       | tqdm                | 4.32.2               | #132
     | pypi       | selenium            | 3.141.0              | #133
     | pypi       | google-auth-httplib2 | 0.0.3                | #134
     | pypi       | termcolor           | 1.1.0                | #135
     | pypi       | kiwisolver          | 1.1.0                | #136
     | pypi       | html5lib            | 1.0.1                | #137
     | pypi       | async-timeout       | 3.0.1                | #138
     | pypi       | bleach              | 3.1.0                | #139
     | pypi       | pickleshare         | 0.7.5                | #140
     | pypi       | tzlocal             | 2.0.0                | #141
     | pypi       | opencv-python       | 4.1.0.25             | #142
     | pypi       | scandir             | 1.10.0               | #143
     | pypi       | pylint              | 2.3.1                | #144
     | pypi       | retrying            | 1.3.3                | #145
     | pypi       | pymongo             | 3.8.0                | #146
     | pypi       | isort               | 4.3.21               | #147
     | pypi       | singledispatch      | 3.4.0.3              | #148
     | pypi       | networkx            | 2.3                  | #149
     | pypi       | cycler              | 0.10.0               | #150
     | pypi       | scikit-image        | 0.15.0               | #151
     | pypi       | tensorflow          | 1.14.0               | #152
     | pypi       | requests-toolbelt   | 0.9.1                | #153
     | pypi       | astroid             | 2.2.5                | #154
     | pypi       | dask                | 2.2.0                | #155
     | pypi       | tabulate            | 0.8.3                | #156
     | pypi       | h5py                | 2.9.0                | #158
     | pypi       | trueskill           | 0.4.5                | #159
     | pypi       | pykube              | 0.15.0               | #160
     | pypi       | cached-property     | 1.5.1                | #161
     | pypi       | webencodings        | 0.5.1                | #162
     | pypi       | lockfile            | 0.12.2               | #163
     | pypi       | tensorboard         | 1.14.0               | #164
     | pypi       | datadog             | 0.29.3               | #165
     | pypi       | websockets          | 8.0.2                | #166
     | pypi       | gitpython           | 2.1.13               | #167
     | pypi       | apache-beam         | 2.14.0               | #168
     | pypi       | pyzmq               | 18.0.2               | #169
     | pypi       | defusedxml          | 0.6.0                | #170
     | pypi       | subprocess32        | 3.5.4                | #172
     | pypi       | twisted             | 19.7.0               | #173
     | pypi       | simplegeneric       | 0.8.1                | #174
     | pypi       | gitdb2              | 2.0.5                | #175
     | pypi       | docker-compose      | 1.24.1               | #176
     | pypi       | smmap2              | 2.0.5                | #177
     | pypi       | astor               | 0.8.0                | #178
     | pypi       | raven               | 6.10.0               | #179
     | pypi       | pytest-cov          | 2.7.1                | #180
     | pypi       | incremental         | 17.5.0               | #181
     | pypi       | gast                | 0.2.2                | #182
     | pypi       | elasticsearch-dsl   | 7.0.0                | #183
     | pypi       | azure-common        | 1.1.23               | #184
     | pypi       | arrow               | 0.14.4               | #185
     | pypi       | amqp                | 2.5.0                | #187
     | pypi       | hdfs                | 2.5.8                | #188
     | pypi       | kombu               | 4.6.3                | #189
     | pypi       | pycrypto            | 2.6.1                | #190
     | pypi       | isodate             | 0.6.0                | #191
     | pypi       | jupyter-core        | 4.5.0                | #192
     | pypi       | entrypoints         | 0.3                  | #193
     | pypi       | ordereddict         | 1.1                  | #194
     | pypi       | nbformat            | 4.4.0                | #195
     | pypi       | vcversioner         | 2.16.0.0             | #196
     | pypi       | xmltodict           | 0.12.0               | #197
     | pypi       | unidecode           | 1.1.1                | #198
     | pypi       | alabaster           | 0.7.12               | #199
     | pypi       | appdirs             | 1.4.3                | #200
     | pypi       | celery              | 4.3.0                | #201
     | pypi       | contextlib2         | 0.5.5                | #202
     | pypi       | pypng               | 0.0.20               | #203
     | pypi       | snowballstemmer     | 1.9.0                | #204
     | pypi       | psycopg2-binary     | 2.8.3                | #205
     | pypi       | billiard            | 3.6.0.0              | #206
     | pypi       | dill                | 0.3.0                | #207
     | pypi       | mako                | 1.1.0                | #208
     | pypi       | monotonic           | 1.5                  | #209
     | pypi       | texttable           | 1.6.2                | #210
     | pypi       | hiredis             | 1.0.0                | #211
     | pypi       | sphinx              | 2.1.2                | #212
     | pypi       | azure-nspkg         | 3.0.2                | #213
     | pypi       | keras-preprocessing | 1.1.0                | #214
     | pypi       | keras-applications  | 1.0.8                | #215
     | pypi       | jedi                | 0.14.1               | #216
     | pypi       | parso               | 0.5.1                | #217
     | pypi       | prettytable         | 0.7.2                | #218
     | pypi       | backports-abc       | 0.5                  | #219
     | pypi       | typed-ast           | 1.4.0                | #220
     | pypi       | jsonpickle          | 1.2                  | #221
     | pypi       | xlrd                | 1.2.0                | #222
     | pypi       | keras               | 2.2.4                | #223
     | pypi       | dockerpty           | 0.4.1                | #224
     | pypi       | pywavelets          | 1.0.3                | #225
     | pypi       | ansible             | 2.8.3                | #226
     | pypi       | imagesize           | 1.1.0                | #228
     | pypi       | msgpack             | 0.6.1                | #229
     | pypi       | regex               | 2019.06.08           | #230
     | pypi       | sphinxcontrib-websupport | 1.1.2                | #231
     | pypi       | croniter            | 0.3.30               | #232
     | pypi       | ply                 | 3.11                 | #233
     | pypi       | sortedcontainers    | 2.1.0                | #234
     | pypi       | vine                | 1.3.0                | #235
     | pypi       | linecache2          | 1.0.0                | #236
     | pypi       | netaddr             | 0.7.19               | #237
     | pypi       | traceback2          | 1.4.0                | #238
     | pypi       | unicodecsv          | 0.14.1               | #239
     | pypi       | pycryptodome        | 3.8.2                | #240
     | pypi       | unittest2           | 1.1.0                | #241
     | pypi       | pyserial            | 3.4                  | #242
     | pypi       | google-cloud-firestore | 1.4.0                | #243
     | pypi       | statsd              | 3.3.0                | #244
     | pypi       | py4j                | 0.10.8.1             | #245
     | pypi       | mistune             | 0.8.4                | #246
     | pypi       | nltk                | 3.4.4                | #247
     | pypi       | djangorestframework | 3.10.2               | #248
     | pypi       | pypandoc            | 1.4                  | #249
     | pypi       | prometheus-client   | 0.7.1                | #250
     | pypi       | ipykernel           | 5.1.1                | #251
     | pypi       | jupyter-client      | 5.3.1                | #252
     | pypi       | google-cloud-logging | 1.12.1               | #253
     | pypi       | python-daemon       | 2.2.3                | #254
     | pypi       | thrift              | 0.11.0               | #255
     | pypi       | alembic             | 1.0.11               | #256
     | pypi       | ecdsa               | 0.13.2               | #257
     | pypi       | dnspython           | 1.16.0               | #258
     | pypi       | toml                | 0.10.0               | #259
     | pypi       | openpyxl            | 2.6.2                | #260
     | pypi       | notebook            | 6.0.0                | #261
     | pypi       | tox                 | 3.13.2               | #262
     | pypi       | backcall            | 0.1.0                | #265
     | pypi       | ndg-httpsclient     | 0.5.1                | #266
     | pypi       | iso8601             | 0.1.12               | #267
     | pypi       | adal                | 1.2.2                | #268
     | pypi       | terminado           | 0.8.2                | #269
     | pypi       | python-editor       | 1.0.4                | #270
     | pypi       | nbconvert           | 5.5.0                | #271
     | pypi       | jdcal               | 1.4.1                | #272
     | pypi       | testpath            | 0.4.2                | #273
     | pypi       | xlsxwriter          | 1.1.8                | #274
     | pypi       | ipywidgets          | 7.5.1                | #275
     | pypi       | send2trash          | 1.5.0                | #276
     | pypi       | widgetsnbextension  | 3.5.1                | #277
     | pypi       | pycryptodomex       | 3.8.2                | #278
     | pypi       | bz2file             | 0.98                 | #279
     | pypi       | google-cloud-datastore | 1.9.0                | #280
     | pypi       | pandocfilters       | 1.4.2                | #281
     | pypi       | yarl                | 1.3.0                | #282
     | pypi       | sqlparse            | 0.3.0                | #283
     | pypi       | smart-open          | 1.8.4                | #284
     | pypi       | mysqlclient         | 1.4.2.post1          | #285
     | pypi       | et-xmlfile          | 1.0.1                | #286
     | pypi       | stevedore           | 1.30.1               | #287
     | pypi       | gapic-google-cloud-logging-v2 | 0.91.3               | #288
     | pypi       | shapely             | 1.6.4.post2          | #289
     | pypi       | azure-storage-common | 2.1.0                | #290
     | pypi       | python-magic        | 0.4.15               | #291
     | pypi       | pyhamcrest          | 1.9.0                | #292
     | pypi       | msrest              | 0.6.9                | #293
     | pypi       | aniso8601           | 7.0.0                | #294
     | pypi       | qtconsole           | 4.5.2                | #295
     | pypi       | pycurl              | 7.43.0.3             | #296
     | pypi       | plotly              | 4.1.0                | #297
     | pypi       | altgraph            | 0.16.1               | #298
     | pypi       | msgpack-python      | 0.5.6                | #299
     | pypi       | proto-google-cloud-logging-v2 | 0.91.3               | #300
     | pypi       | python-pam          | 1.8.4                | #301
     | pypi       | keyring             | 19.0.2               | #302
     | pypi       | macholib            | 1.11                 | #303
     | pypi       | whichcraft          | 0.6.0                | #304
     | pypi       | binaryornot         | 0.4.4                | #305
     | pypi       | netifaces           | 0.10.9               | #306
     | pypi       | flask-cors          | 3.0.8                | #307
     | pypi       | poyo                | 0.5.0                | #308
     | pypi       | inflection          | 0.3.1                | #309
     | pypi       | nvidia-ml-py3       | 7.352.0              | #310
     | pypi       | cookiecutter        | 1.6.0                | #311
     | pypi       | jinja2-time         | 0.2.0                | #312
     | pypi       | configobj           | 5.0.6                | #313
     | pypi       | azure-storage-blob  | 2.1.0                | #314
     | pypi       | google-cloud-pubsub | 0.45.0               | #315
     | pypi       | statsmodels         | 0.10.1               | #316
     | pypi       | msrestazure         | 0.6.1                | #317
     | pypi       | pep8                | 1.7.1                | #318
     | pypi       | pyhocon             | 0.3.51               | #319
     | pypi       | faker               | 2.0.0                | #320
     | pypi       | uvloop              | 0.12.2               | #321
     | pypi       | jupyter-console     | 6.0.0                | #322
     | pypi       | manhole             | 1.6.0                | #323
     | pypi       | google-auth-oauthlib | 0.4.0                | #324
     | pypi       | uwsgi               | 2.0.18               | #325
     | pypi       | jupyter             | 1.0.0                | #326
     | pypi       | virtualenv-clone    | 0.5.3                | #327
     | pypi       | ptvsd               | 4.3.0                | #328
     | pypi       | google-gax          | 0.16.0               | #329
     | pypi       | pystache            | 0.5.4                | #330
     | pypi       | xgboost             | 0.90                 | #331
     | pypi       | webob               | 1.8.5                | #332
     | pypi       | ua-parser           | 0.8.0                | #333
     | pypi       | ijson               | 2.4                  | #334
     | pypi       | pydevd              | 1.6.1                | #335
     | pypi       | patsy               | 0.5.1                | #336
     | pypi       | grpc-google-iam-v1  | 0.12.3               | #337
     | pypi       | flask-sqlalchemy    | 2.4.0                | #338
     | pypi       | python-jose         | 3.0.1                | #339
     | pypi       | pysocks             | 1.7.0                | #340
     | pypi       | cssselect           | 1.0.3                | #341
     | pypi       | constantly          | 15.1.0               | #342
     | pypi       | marshmallow         | 2.19.5               | #343
     | pypi       | ccxt                | 1.18.1022            | #344
     | pypi       | s3fs                | 0.3.1                | #345
     | pypi       | argcomplete         | 1.10.0               | #346
     | pypi       | automat             | 0.7.0                | #347
     | pypi       | azure-storage       | 0.36.0               | #348
     | pypi       | theano              | 1.0.4                | #349
     | pypi       | capstone            | 4.0.1                | #350
     | pypi       | bs4                 | 0.0.1                | #351
     | pypi       | filelock            | 3.0.12               | #352
     | pypi       | pager               | 3.3                  | #353
     | pypi       | hyperlink           | 19.0.0               | #354
     | pypi       | wtforms             | 2.2.1                | #355
     | pypi       | parsedatetime       | 2.4                  | #356
     | pypi       | text-unidecode      | 1.2                  | #357
     | pypi       | cookiejar           | 0.0.2                | #358
     | pypi       | pipenv              | 2018.11.26           | #359
     | pypi       | fuzzywuzzy          | 0.17.0               | #360
     | pypi       | humanfriendly       | 4.18                 | #361
     | pypi       | oauth               | 1.0.1                | #362
     | pypi       | apipkg              | 1.5                  | #363
     | pypi       | blinker             | 1.4                  | #364
     | pypi       | autopep8            | 1.4.4                | #365
     | pypi       | seaborn             | 0.9.0                | #366
     | pypi       | snowflake-connector-python | 1.8.6                | #367
     | pypi       | cheetah             | 2.4.4                | #368
     | pypi       | newrelic            | 5.0.0.124            | #369
     | pypi       | applicationinsights | 0.11.9               | #370
     | pypi       | seqlogo             | 5.29.4               | #371
     | pypi       | flask-wtf           | 0.14.2               | #372
     | pypi       | execnet             | 1.6.1                | #373
     | pypi       | configargparse      | 0.14.0               | #374
     | pypi       | django-extensions   | 2.2.1                | #375
     | pypi       | grpcio-tools        | 1.22.0               | #376
     | pypi       | pathspec            | 0.5.9                | #377
     | pypi       | cherrypy            | 18.1.2               | #378
     | pypi       | mysql-python        | 1.2.5                | #379
     | pypi       | supervisor          | 4.0.4                | #380
     | pypi       | slackclient         | 2.1.0                | #381
     | pypi       | azure-mgmt-resource | 3.1.0                | #382
     | pypi       | cloudpickle         | 1.2.1                | #383
     | pypi       | service-identity    | 18.1.0               | #384
     | pypi       | fasteners           | 0.15                 | #385
     | pypi       | joblib              | 0.13.2               | #386
     | pypi       | azure-storage-nspkg | 3.1.0                | #387
     | pypi       | django-filter       | 2.2.0                | #388
     | pypi       | azure-mgmt-storage  | 4.0.0                | #389
     | pypi       | gspread             | 3.1.0                | #390
     | pypi       | pika                | 1.1.0                | #391
     | pypi       | soupsieve           | 1.9.2                | #392
     | pypi       | google-cloud-bigtable | 0.34.0               | #393
     | pypi       | package             | 0.1.1                | #394
     | pypi       | azure-mgmt-nspkg    | 3.0.2                | #395
     | pypi       | pydot               | 1.4.1                | #396
     | pypi       | meld3               | 1.0.2                | #397
     | pypi       | django-cors-headers | 3.0.2                | #398
     | pypi       | pytest-xdist        | 1.29.0               | #399
     | pypi       | codecov             | 2.0.15               | #400
     | pypi       | secretstorage       | 3.1.1                | #401
     | pypi       | gym                 | 0.14.0               | #402
     | pypi       | freezegun           | 0.3.12               | #403
     | pypi       | cheroot             | 6.5.5                | #404
     | pypi       | tenacity            | 5.0.4                | #405
     | pypi       | google-cloud-vision | 0.38.1               | #406
     | pypi       | sphinx-rtd-theme    | 0.4.3                | #407
     | pypi       | responses           | 0.10.6               | #408
     | pypi       | graphviz            | 0.11.1               | #409
     | pypi       | pyrfc3339           | 1.1                  | #410
     | pypi       | watchdog            | 0.9.0                | #411
     | pypi       | tempora             | 1.14.1               | #412
     | pypi       | geopy               | 1.20.0               | #413
     | pypi       | python-mimeparse    | 1.6.0                | #414
     | pypi       | portend             | 2.5                  | #415
     | pypi       | docker-py           | 1.10.6               | #416
     | pypi       | flask-restful       | 0.3.7                | #417
     | pypi       | kazoo               | 2.6.1                | #418
     | pypi       | passlib             | 1.7.1                | #419
     | pypi       | django-storages     | 1.7.1                | #420
     | pypi       | reportlab           | 3.5.23               | #421
     | pypi       | pyarrow             | 0.14.1               | #422
     | pypi       | bottle              | 0.12.17              | #423
     | pypi       | pytest-mock         | 1.10.4               | #424
     | pypi       | maxminddb           | 1.4.1                | #425
     | pypi       | kubernetes          | 10.0.0               | #426
     | pypi       | gensim              | 3.8.0                | #428
     | pypi       | google-cloud-monitoring | 0.32.0               | #429
     | pypi       | argh                | 0.26.2               | #430
     | pypi       | voluptuous          | 0.11.5               | #432
     | pypi       | factory-boy         | 2.12.0               | #433
     | pypi       | azure-mgmt-containerregistry | 2.8.0                | #435
     | pypi       | pathlib             | 1.0.1                | #436
     | pypi       | user-agents         | 2.0                  | #437
     | pypi       | s3cmd               | 2.0.2                | #438
     | pypi       | azure-mgmt-authorization | 0.60.0               | #439
     | pypi       | azure-mgmt-compute  | 6.0.0                | #440
     | pypi       | azure-mgmt-network  | 4.0.0                | #441
     | pypi       | django-debug-toolbar | 2.0                  | #442
     | pypi       | tldextract          | 2.2.1                | #443
     | pypi       | azure-datalake-store | 0.0.46               | #444
     | pypi       | olefile             | 0.46                 | #445
     | pypi       | python-levenshtein  | 0.12.0               | #446
     | pypi       | pyspark             | 2.4.3                | #447
     | pypi       | azure-mgmt-keyvault | 2.0.0                | #448
     | pypi       | gapic-google-cloud-datastore-v1 | 0.90.4               | #449
     | pypi       | backoff             | 1.8.0                | #451
     | pypi       | munch               | 2.3.2                | #452
     | pypi       | cookies             | 2.2.1                | #453
     | pypi       | josepy              | 1.2.0                | #454
     | pypi       | google-cloud-spanner | 1.10.0               | #455
     | pypi       | deepdiff            | 4.0.7                | #456
     | pypi       | acme                | 0.37.0               | #457
     | pypi       | pyaml               | 19.4.1               | #458
     | pypi       | google-cloud        | 0.34.0               | #460
     | pypi       | pytest-forked       | 1.0.2                | #461
     | pypi       | python-slugify      | 3.0.3                | #462
     | pypi       | geoip2              | 2.9.0                | #463
     | pypi       | requests-file       | 1.4.3                | #464
     | pypi       | python-augeas       | 1.0.3                | #465
     | pypi       | certbot             | 0.37.0               | #466
     | pypi       | fabric              | 2.5.0                | #467
     | pypi       | avro                | 1.9.0                | #468
     | pypi       | google-cloud-language | 1.3.0                | #469
     | pypi       | pathtools           | 0.1.2                | #470
     | pypi       | anyjson             | 0.3.3                | #471
     | pypi       | waitress            | 1.3.0                | #472
     | pypi       | xlwt                | 1.3.0                | #473
     | pypi       | jws                 | 0.1.3                | #474
     | pypi       | requests-mock       | 1.6.0                | #475
     | pypi       | google-cloud-translate | 1.6.0                | #476
     | pypi       | flask-login         | 0.4.1                | #477
     | pypi       | requests-aws4auth   | 0.9                  | #478
     | pypi       | cassandra-driver    | 3.18.0               | #479
     | pypi       | jsonpointer         | 2.0                  | #480
     | pypi       | google-cloud-speech | 1.2.0                | #481
     | pypi       | certbot-apache      | 0.37.0               | #482
     | pypi       | python-dotenv       | 0.10.3               | #483
     | pypi       | letsencrypt         | 0.7.0                | #484
     | pypi       | python-jwt          | 3.2.4                | #485
     | pypi       | python-memcached    | 1.59                 | #486
     | pypi       | google-apitools     | 0.5.30               | #487
     | pypi       | dicttoxml           | 1.7.4                | #488
     | pypi       | tensorflow-tensorboard | 1.5.1                | #489
     | pypi       | google-cloud-error-reporting | 0.32.0               | #490
     | pypi       | pyodbc              | 4.0.27               | #491
     | pypi       | feedparser          | 5.2.1                | #492
     | pypi       | pyperclip           | 1.7.0                | #495
     | pypi       | google-cloud-resource-manager | 0.29.2               | #496
     | pypi       | mypy                | 0.720                | #497
     | pypi       | pendulum            | 2.0.5                | #498
     | pypi       | google-cloud-dns    | 0.30.2               | #499
     | pypi       | pytest-timeout      | 1.3.3                | #500
     | pypi       | certbot-nginx       | 0.37.0               | #501
     | pypi       | pip-tools           | 4.0.0                | #502
     | pypi       | google-cloud-runtimeconfig | 0.29.2               | #503
     | pypi       | django-environ      | 0.4.5                | #504
     | pypi       | pkginfo             | 1.5.0.1              | #505
     | pypi       | debtcollector       | 1.21.0               | #506
     | pypi       | geographiclib       | 1.49                 | #507
     | pypi       | fastavro            | 0.22.3               | #508
     | pypi       | semver              | 2.8.1                | #509
     | pypi       | google-cloud-videointelligence | 1.10.0               | #511
     | pypi       | jira                | 2.0.0                | #512
     | pypi       | azure-graphrbac     | 0.61.1               | #513
     | pypi       | cytoolz             | 0.10.0               | #514
     | pypi       | ipdb                | 0.12.2               | #515
     | pypi       | python-json-logger  | 0.1.11               | #516
     | pypi       | azure-mgmt-rdbms    | 1.9.0                | #517
     | pypi       | paho-mqtt           | 1.4.0                | #518
     | pypi       | pysftp              | 0.2.9                | #519
     | pypi       | azure-mgmt-dns      | 3.0.0                | #520
     | pypi       | w3lib               | 1.20.0               | #521
     | pypi       | semantic-version    | 2.6.0                | #522
     | pypi       | scp                 | 0.13.2               | #523
     | pypi       | retry               | 0.9.2                | #524
     | pypi       | coreapi             | 2.3.3                | #525
     | pypi       | azure-keyvault      | 1.1.0                | #526
     | pypi       | pytzdata            | 2019.2               | #527
     | pypi       | pycountry           | 19.7.15              | #528
     | pypi       | zeep                | 3.4.0                | #530
     | pypi       | jpype1              | 0.7.0                | #531
     | pypi       | pyhive              | 0.6.1                | #532
     | pypi       | moto                | 1.3.13               | #533
     | pypi       | kafka-python        | 1.4.6                | #534
     | pypi       | pytest-django       | 3.5.1                | #535
     | pypi       | eventlet            | 0.25.0               | #536
     | pypi       | phonenumbers        | 8.10.16              | #537
     | pypi       | rfc3986             | 1.3.2                | #538
     | pypi       | coreschema          | 0.0.4                | #540
     | pypi       | webtest             | 2.0.33               | #541
     | pypi       | itypes              | 1.1.0                | #542
     | pypi       | colorlog            | 4.0.2                | #543
     | pypi       | suds-jurko          | 0.6                  | #544
     | pypi       | jsonpatch           | 1.24                 | #545
     | pypi       | coloredlogs         | 10.0                 | #546
     | pypi       | parse               | 1.12.0               | #547
     | pypi       | azure-mgmt-containerinstance | 1.5.0                | #548
     | pypi       | idna-ssl            | 1.1.0                | #549
     | pypi       | enum                | 0.4.7                | #550
     | pypi       | graphql-core        | 2.2.1                | #551
     | pypi       | frida               | 12.6.12              | #552
     | pypi       | jsondiff            | 1.2.0                | #553
     | pypi       | qds-sdk             | 1.12.0               | #554
     | pypi       | pymssql             | 2.1.4                | #555
     | pypi       | sh                  | 1.12.14              | #556
     | pypi       | hypothesis          | 4.32.3               | #557
     | pypi       | cmd2                | 0.9.15               | #558
     | pypi       | dictdiffer          | 0.8.0                | #559
     | pypi       | blessings           | 1.7                  | #561
     | pypi       | humanize            | 0.5.1                | #562
     | pypi       | influxdb            | 5.2.2                | #563
     | pypi       | testtools           | 2.3.0                | #564
     | pypi       | bokeh               | 1.3.4                | #565
     | pypi       | setproctitle        | 1.1.10               | #566
     | pypi       | youtube-dl          | 2019.8.2             | #567
     | pypi       | azure-mgmt-containerservice | 6.0.0                | #568
     | pypi       | gapic-google-cloud-error-reporting-v1beta1 | 0.15.3               | #569
     | pypi       | numexpr             | 2.6.9                | #570
     | pypi       | libtmux             | 0.8.2                | #571
     | pypi       | stripe              | 2.33.2               | #572
     | pypi       | keystoneauth1       | 3.15.0               | #573
     | pypi       | spacy               | 2.1.7                | #574
     | pypi       | proto-google-cloud-error-reporting-v1beta1 | 0.15.3               | #575
     | pypi       | thinc               | 7.0.8                | #576
     | pypi       | pypdf2              | 1.26.0               | #577
     | pypi       | sasl                | 0.2.1                | #578
     | pypi       | python-gflags       | 3.1.2                | #579
     | pypi       | azure-cli-core      | 2.0.70               | #580
     | pypi       | extras              | 1.0.0                | #581
     | pypi       | coveralls           | 1.8.2                | #582
     | pypi       | preshed             | 2.0.1                | #583
     | pypi       | murmurhash          | 1.0.2                | #584
     | pypi       | tensorflow-gpu      | 1.14.0               | #585
     | pypi       | django-redis        | 4.10.0               | #586
     | pypi       | parsel              | 1.5.1                | #587
     | pypi       | cymem               | 2.0.2                | #588
     | pypi       | cliff               | 2.15.0               | #589
     | pypi       | azure-mgmt-batch    | 6.0.0                | #590
     | pypi       | python-jenkins      | 1.5.0                | #591
     | pypi       | python-geohash      | 0.8.5                | #592
     | pypi       | aws-xray-sdk        | 2.4.2                | #593
     | pypi       | fixtures            | 3.0.0                | #594
     | pypi       | google-cloud-trace  | 0.22.0               | #595
     | pypi       | pydocstyle          | 4.0.0                | #596
     | pypi       | requests-futures    | 1.0.0                | #597
     | pypi       | azure-batch         | 7.0.0                | #598
     | pypi       | asyncpg             | 0.18.3               | #599
     | pypi       | proto-google-cloud-datastore-v1 | 0.90.4               | #600
     | pypi       | msgpack-numpy       | 0.4.4.3              | #601
     | pypi       | azure-mgmt-batchai  | 2.0.0                | #602
     | pypi       | flask-migrate       | 2.5.2                | #603
     | pypi       | azure-mgmt-reservations | 0.3.2                | #604
     | pypi       | azure-mgmt-msi      | 1.0.0                | #605
     | pypi       | haversine           | 2.1.2                | #606
     | pypi       | pyrsistent          | 0.15.4               | #607
     | pypi       | wandb               | 0.8.6                | #608
     | pypi       | twilio              | 6.29.3               | #609
     | pypi       | tensorflow-metadata | 0.14.0               | #610
     | pypi       | django-appconf      | 1.0.3                | #611
     | pypi       | knack               | 0.6.3                | #612
     | pypi       | azure-mgmt-datalake-store | 0.5.0                | #613
     | pypi       | flask-restplus      | 0.12.1               | #614
     | pypi       | scrapy              | 1.7.3                | #615
     | pypi       | queuelib            | 1.5.0                | #616
     | pypi       | pyxdg               | 0.26                 | #617
     | pypi       | setuptools-git      | 1.2                  | #618
     | pypi       | azure-mgmt-loganalytics | 0.2.0                | #619
     | pypi       | azure-mgmt-datalake-nspkg | 3.0.1                | #620
     | pypi       | flask-script        | 2.0.6                | #621
     | pypi       | datetime            | 4.3                  | #622
     | pypi       | paste               | 3.1.0                | #623
     | pypi       | plac                | 1.1.0                | #624
     | pypi       | python-consul       | 1.1.0                | #625
     | pypi       | azure-mgmt-web      | 0.42.0               | #626
     | pypi       | dateparser          | 0.7.1                | #627
     | pypi       | google-cloud-container | 0.3.0                | #628
     | pypi       | azure-mgmt-sql      | 0.12.0               | #629
     | pypi       | pycountry-convert   | 0.7.2                | #630
     | pypi       | simple-salesforce   | 0.74.3               | #631
     | pypi       | azure-mgmt-cdn      | 3.1.0                | #632
     | pypi       | pydispatcher        | 2.0.5                | #633
     | pypi       | mysql-connector-python | 8.0.17               | #634
     | pypi       | pypiwin32           | 223                  | #635
     | pypi       | yamllint            | 1.16.0               | #636
     | pypi       | google-cloud-bigquery-datatransfer | 0.4.1                | #637
     | pypi       | strict-rfc3339      | 0.7                  | #639
     | pypi       | portalocker         | 1.5.1                | #640
     | pypi       | invoke              | 1.3.0                | #641
     | pypi       | azure-mgmt-redis    | 6.0.0                | #642
     | pypi       | distro              | 1.4.0                | #643
     | pypi       | whitenoise          | 4.1.3                | #644
     | pypi       | pulp                | 1.6.10               | #645
     | pypi       | crcmod              | 1.7                  | #646
     | pypi       | cx-oracle           | 7.2.1                | #647
     | pypi       | pympler             | 0.7                  | #648
     | pypi       | azure-mgmt-monitor  | 0.7.0                | #649
     | pypi       | torch               | 1.1.0.post2          | #650
     | pypi       | pkgconfig           | 1.5.1                | #651
     | pypi       | robotframework      | 3.1.2                | #652
     | pypi       | multi-key-dict      | 2.0.3                | #653
     | pypi       | azure-servicebus    | 0.50.1               | #654
     | pypi       | azure-cli-nspkg     | 3.0.4                | #655
     | pypi       | slacker             | 0.13.0               | #656
     | pypi       | sqlalchemy-utils    | 0.34.1               | #657
     | pypi       | azure-mgmt-cognitiveservices | 5.0.0                | #658
     | pypi       | dj-database-url     | 0.5.0                | #659
     | pypi       | pyathenajdbc        | 2.0.5                | #660
     | pypi       | azure-mgmt-trafficmanager | 0.51.0               | #661
     | pypi       | python-keystoneclient | 3.20.0               | #662
     | pypi       | graypy              | 1.2.0                | #663
     | pypi       | pywin32             | 224                  | #664
     | pypi       | html2text           | 2018.1.9             | #665
     | pypi       | mmh3                | 2.5.1                | #666
     | pypi       | ldap3               | 2.6                  | #667
     | pypi       | flower              | 0.9.3                | #669
     | pypi       | pystan              | 2.19.0.0             | #670
     | pypi       | zmq                 | 0.0.0                | #671
     | pypi       | python-ldap         | 3.2.0                | #672
     | pypi       | schedule            | 0.6.0                | #673
     | pypi       | thrift-sasl         | 0.3.0                | #674
     | pypi       | pandas-gbq          | 0.11.0               | #675
     | pypi       | sendgrid            | 6.0.5                | #676
     | pypi       | pyproj              | 2.2.1                | #677
     | pypi       | beautifulsoup       | 3.2.1                | #678
     | pypi       | openstacksdk        | 0.32.0               | #679
     | pypi       | mypy-extensions     | 0.4.1                | #680
     | pypi       | python-subunit      | 1.3.0                | #681
     | pypi       | azure-mgmt-cosmosdb | 0.7.0                | #682
     | pypi       | pdfminer            | 20140328             | #683
     | pypi       | promise             | 2.2.1                | #684
     | pypi       | azure-cli-profile   | 2.1.5                | #685
     | pypi       | parse-type          | 0.5.2                | #686
     | pypi       | yapf                | 0.28.0               | #687
     | pypi       | gdata               | 2.0.18               | #688
     | pypi       | deprecation         | 2.0.6                | #689
     | pypi       | azure-mgmt-datalake-analytics | 0.6.0                | #690
     | pypi       | hvac                | 0.9.5                | #691
     | pypi       | google-compute-engine | 2.8.13               | #692
     | pypi       | azure-mgmt-iothub   | 0.8.2                | #693
     | pypi       | azure-mgmt-devtestlabs | 4.0.0                | #694
     | pypi       | llvmlite            | 0.29.0               | #695
     | pypi       | swagger-spec-validator | 2.4.3                | #696
     | pypi       | os-service-types    | 1.7.0                | #697
     | pypi       | pytest-html         | 1.22.0               | #698
     | pypi       | pygithub            | 1.43.8               | #699
     | pypi       | pyvmomi             | 6.7.1.2018.12        | #700
     | pypi       | apscheduler         | 3.6.1                | #701
     | pypi       | pastedeploy         | 2.0.1                | #702
     | pypi       | azure-cli-command-modules-nspkg | 2.0.3                | #703
     | pypi       | easyprocess         | 0.2.7                | #704
     | pypi       | nose-exclude        | 0.5.0                | #705
     | pypi       | credstash           | 1.15.0               | #706
     | pypi       | redis-py-cluster    | 1.3.6                | #707
     | pypi       | sentry-sdk          | 0.10.2               | #708
     | pypi       | terminaltables      | 3.1.0                | #709
     | pypi       | fiona               | 1.8.6                | #710
     | pypi       | pyinotify           | 0.9.6                | #711
     | pypi       | python3-openid      | 3.1.0                | #712
     | pypi       | baselines           | 0.1.5                | #713
     | pypi       | mxnet               | 1.5.0                | #714
     | pypi       | httpretty           | 0.9.6                | #715
     | pypi       | sshtunnel           | 0.1.5                | #716
     | pypi       | mpmath              | 1.1.0                | #717
     | pypi       | openapi-codec       | 1.3.2                | #718
     | pypi       | azure-mgmt-iothubprovisioningservices | 0.2.0                | #719
     | pypi       | suds                | 0.4                  | #720
     | pypi       | pip-lock            | 2.0.0                | #721
     | pypi       | azure-servicemanagement-legacy | 0.20.6               | #723
     | pypi       | azure-mgmt-servicefabric | 0.3.0                | #724
     | pypi       | numba               | 0.45.1               | #725
     | pypi       | azure-cli-telemetry | 1.0.3                | #726
     | pypi       | twine               | 1.13.0               | #727
     | pypi       | cligj               | 0.5.0                | #728
     | pypi       | python-docx         | 0.8.10               | #729
     | pypi       | azure-mgmt          | 4.0.0                | #730
     | pypi       | pydocumentdb        | 2.3.3                | #731
     | pypi       | azure-cli-resource  | 2.1.16               | #732
     | pypi       | azure-cli-acs       | 2.4.4                | #733
     | pypi       | azure-cli-vm        | 2.2.23               | #734
     | pypi       | s2sphere            | 0.2.5                | #735
     | pypi       | azure-cli-network   | 2.5.2                | #736
     | pypi       | azure               | 4.0.0                | #737
     | pypi       | azure-cli-storage   | 2.4.3                | #738
     | pypi       | findspark           | 1.3.0                | #739
     | pypi       | azure-mgmt-eventhub | 3.0.0                | #740
     | pypi       | cachecontrol        | 0.12.5               | #741
     | pypi       | flake8-polyfill     | 1.0.2                | #742
     | pypi       | azure-cli-acr       | 2.2.9                | #743
     | pypi       | azure-cli-sql       | 2.2.5                | #744
     | pypi       | azure-mgmt-marketplaceordering | 0.2.1                | #745
     | pypi       | tblib               | 1.4.0                | #746
     | pypi       | unittest-xml-reporting | 2.5.1                | #747
     | pypi       | brotlipy            | 0.7.0                | #748
     | pypi       | googleads           | 20.0.0               | #749
     | pypi       | azure-cli-interactive | 0.4.5                | #750
     | pypi       | behave              | 1.2.6                | #751
     | pypi       | python-novaclient   | 14.2.0               | #752
     | pypi       | azure-cli-iot       | 0.3.11               | #753
     | pypi       | filechunkio         | 1.8                  | #754
     | pypi       | azure-mgmt-eventgrid | 2.2.0                | #755
     | pypi       | azure-cli-batch     | 4.0.3                | #756
     | pypi       | cssutils            | 1.0.2                | #757
     | pypi       | azure-mgmt-recoveryservices | 0.4.0                | #758
     | pypi       | appnope             | 0.1.0                | #759
     | pypi       | azure-mgmt-consumption | 3.0.0                | #760
     | pypi       | azure-mgmt-recoveryservicesbackup | 0.4.0                | #761
     | pypi       | azure-mgmt-advisor  | 2.0.1                | #762
     | pypi       | azure-mgmt-billing  | 0.2.0                | #763
     | pypi       | gcloud              | 0.18.3               | #764
     | pypi       | django-model-utils  | 3.2.0                | #765
     | pypi       | requestsexceptions  | 1.4.0                | #766
     | pypi       | mysql-connector     | 2.2.9                | #767
     | pypi       | azure-mgmt-servicebus | 0.6.0                | #768
     | pypi       | imageio             | 2.5.0                | #769
     | pypi       | click-plugins       | 1.1.1                | #770
     | pypi       | sympy               | 1.4                  | #771
     | pypi       | python-nmap         | 0.6.1                | #772
     | pypi       | pattern             | 3.6                  | #773
     | pypi       | cairocffi           | 1.0.2                | #774
     | pypi       | opentracing         | 2.2.0                | #775
     | pypi       | pysqlite            | 2.8.3                | #776
     | pypi       | databricks-cli      | 0.8.7                | #777
     | pypi       | azure-mgmt-media    | 1.1.1                | #778
     | pypi       | protobuf3-to-dict   | 0.1.5                | #779
     | pypi       | os-client-config    | 1.32.0               | #780
     | pypi       | testfixtures        | 6.10.0               | #781
     | pypi       | pefile              | 2019.4.18            | #782
     | pypi       | flask-admin         | 1.5.3                | #783
     | pypi       | django-rest-swagger | 2.2.0                | #784
     | pypi       | pytest-instafail    | 0.4.1                | #785
     | pypi       | azure-cli-appservice | 0.2.21               | #786
     | pypi       | azure-cli-role      | 2.6.4                | #787
     | pypi       | expiringdict        | 1.1.4                | #788
     | pypi       | python-http-client  | 3.1.0                | #789
     | pypi       | simpleflock         | 0.0.3                | #790
     | pypi       | bandit              | 1.6.2                | #791
     | pypi       | azure-cli-keyvault  | 2.2.16               | #792
     | pypi       | azure-cli-container | 0.3.18               | #793
     | pypi       | cairosvg            | 2.4.0                | #794
     | pypi       | multiprocess        | 0.70.8               | #795
     | pypi       | azure-cli-monitor   | 0.2.15               | #796
     | pypi       | azure-mgmt-scheduler | 2.0.0                | #797
     | pypi       | azure-cli-extension | 0.2.5                | #798
     | pypi       | azure-cli-rdbms     | 0.3.12               | #799
     | pypi       | azure-mgmt-logic    | 3.0.0                | #800
     | pypi       | hashids             | 1.2.0                | #801
     | pypi       | azure-cli-dls       | 0.1.10               | #802
     | pypi       | azure-mgmt-search   | 2.1.0                | #803
     | pypi       | azure-cli-dla       | 0.2.6                | #804
     | pypi       | qrcode              | 6.1                  | #805
     | pypi       | azure-cli-lab       | 0.1.8                | #806
     | pypi       | python-swiftclient  | 3.8.0                | #807
     | pypi       | azure-cli-batchai   | 0.4.10               | #808
     | pypi       | translationstring   | 1.3                  | #809
     | pypi       | osc-lib             | 1.13.0               | #810
     | pypi       | torchvision         | 0.3.0                | #811
     | pypi       | statistics          | 1.0.3.5              | #812
     | pypi       | mozlog              | 4.2.0                | #813
     | pypi       | azure-cli-servicefabric | 0.1.20               | #814
     | pypi       | azure-cli-cosmosdb  | 0.2.11               | #815
     | pypi       | azure-cli-cognitiveservices | 0.2.6                | #816
     | pypi       | progressbar2        | 3.42.0               | #817
     | pypi       | inflect             | 2.1.0                | #818
     | pypi       | azure-cli-cdn       | 0.2.4                | #819
     | pypi       | uuid                | 1.30                 | #820
     | pypi       | pyvirtualdisplay    | 0.2.4                | #821
     | pypi       | python-utils        | 2.3.0                | #822
     | pypi       | azure-cli-reservations | 0.4.3                | #823
     | pypi       | geojson             | 2.4.1                | #825
     | pypi       | jsonpath-rw         | 1.4.0                | #826
     | pypi       | jsonfield           | 2.0.2                | #827
     | pypi       | ec2-metadata        | 2.0.0                | #828
     | pypi       | structlog           | 19.1.0               | #829
     | pypi       | nodeenv             | 1.3.3                | #830
     | pypi       | glob2               | 0.7                  | #831
     | pypi       | tensorflow-transform | 0.14.0               | #832
     | pypi       | azure-mgmt-managementgroups | 0.2.0                | #833
     | pypi       | blessed             | 1.15.0               | #834
     | pypi       | cerberus            | 1.3.1                | #835
     | pypi       | cement              | 3.0.4                | #836
     | pypi       | importlib           | 1.0.4                | #837
     | pypi       | lightgbm            | 2.2.3                | #838
     | pypi       | collections-extended | 1.0.2                | #839
     | pypi       | azure-mgmt-datamigration | 3.0.0                | #840
     | pypi       | azure-mgmt-relay    | 0.2.0                | #841
     | pypi       | watchtower          | 0.6.0                | #842
     | pypi       | python-glanceclient | 2.16.0               | #843
     | pypi       | confluent-kafka     | 1.1.0                | #844
     | pypi       | djangorestframework-jwt | 1.11.0               | #845
     | pypi       | python-logstash     | 0.4.6                | #846
     | pypi       | flake8-import-order | 0.18.1               | #847
     | pypi       | typing-extensions   | 3.7.4                | #848
     | pypi       | google-cloud-dataflow | 2.5.0                | #850
     | pypi       | junit-xml           | 1.8                  | #851
     | pypi       | pytest-metadata     | 1.8.0                | #852
     | pypi       | azure-cosmosdb-table | 1.0.5                | #853
     | pypi       | rx                  | 3.0.1                | #854
     | pypi       | win-inet-pton       | 1.1.0                | #855
     | pypi       | azure-cli-configure | 2.0.24               | #856
     | pypi       | jeepney             | 0.4                  | #857
     | pypi       | coala               | 0.11.0               | #858
     | pypi       | pg8000              | 1.13.2               | #859
     | pypi       | azure-cli-cloud     | 2.1.1                | #860
     | pypi       | autobahn            | 19.8.1               | #861
     | pypi       | analytics-python    | 1.2.9                | #862
     | pypi       | azure-multiapi-storage | 0.2.4                | #863
     | pypi       | pynamodb            | 3.4.1                | #864
     | pypi       | pygame              | 1.9.6                | #865
     | pypi       | django-nose         | 1.4.6                | #866
     | pypi       | azure-cli-redis     | 0.4.4                | #867
     | pypi       | ast                 | 0.0.2                | #868
     | pypi       | whoosh              | 2.7.4                | #869
     | pypi       | azure-cli-feedback  | 2.2.1                | #870
     | pypi       | vsts-cd-manager     | 1.0.2                | #871
     | pypi       | odfpy               | 1.4.0                | #873
     | pypi       | mongoengine         | 0.18.2               | #874
     | pypi       | azure-cli-backup    | 1.2.5                | #875
     | pypi       | pygobject           | 3.32.2               | #876
     | pypi       | azure-cli-consumption | 0.4.4                | #877
     | pypi       | azure-cli-find      | 0.3.4                | #878
     | pypi       | urwid               | 2.0.1                | #879
     | pypi       | slackweb            | 1.0.5                | #880
     | pypi       | azure-cli-eventgrid | 0.2.4                | #881
     | pypi       | black               | 19.3b0               | #882
     | pypi       | python-cinderclient | 4.2.1                | #883
     | pypi       | azure-cli-billing   | 0.2.2                | #884
     | pypi       | django-crispy-forms | 1.7.2                | #885
     | pypi       | tablib              | 0.13.0               | #886
     | pypi       | parameterized       | 0.7.0                | #887
     | pypi       | tf-nightly          | 1.15.0.dev20190807   | #888
     | pypi       | azure-cli-advisor   | 2.0.1                | #889
     | pypi       | tinycss2            | 1.0.2                | #890
     | pypi       | brunel              | 2.6.2                | #891
     | pypi       | awsebcli            | 3.15.3               | #892
     | pypi       | cchardet            | 2.1.4                | #893
     | pypi       | azure-cosmosdb-nspkg | 2.0.2                | #894
     | pypi       | cvxopt              | 1.2.3                | #895
     | pypi       | commonmark          | 0.9.0                | #896
     | pypi       | pythonwhois         | 2.4.3                | #897
     | pypi       | azure-mgmt-notificationhubs | 2.1.0                | #898
     | pypi       | rq                  | 1.1.0                | #899
     | pypi       | antlr4-python3-runtime | 4.7.2                | #900
     | pypi       | pygsheets           | 2.0.2                | #901
     | pypi       | luigi               | 2.8.7                | #902
     | pypi       | validate-email      | 1.3                  | #903
     | pypi       | rfc3987             | 1.3.8                | #904
     | pypi       | dulwich             | 0.19.11              | #905
     | pypi       | ddt                 | 1.2.1                | #906
     | pypi       | initools            | 0.3.1                | #907
     | pypi       | shortuuid           | 0.5.0                | #908
     | pypi       | rjsmin              | 1.1.0                | #909
     | pypi       | wordsegment         | 1.3.1                | #910
     | pypi       | bitarray            | 1.0.1                | #911
     | pypi       | azure-storage-queue | 2.1.0                | #912
     | pypi       | pylru               | 1.2.0                | #913
     | pypi       | elasticsearch-curator | 5.7.6                | #914
     | pypi       | pyphen              | 0.9.5                | #915
     | pypi       | flexget             | 2.21.16              | #916
     | pypi       | flask-httpauth      | 3.3.0                | #917
     | pypi       | azure-servicefabric | 6.5.0.0              | #918
     | pypi       | python-openid       | 2.2.5                | #919
     | pypi       | fakeredis           | 1.0.3                | #920
     | pypi       | azure-mgmt-iotcentral | 1.0.0                | #921
     | pypi       | pycairo             | 1.18.1               | #922
     | pypi       | django-compressor   | 2.3                  | #923
     | pypi       | azure-mgmt-policyinsights | 0.3.1                | #924
     | pypi       | pylint-plugin-utils | 0.5                  | #925
     | pypi       | azure-mgmt-maps     | 0.1.0                | #926
     | pypi       | azure-mgmt-signalr  | 0.3.0                | #927
     | pypi       | tempita             | 0.5.2                | #928
     | pypi       | googlemaps          | 3.0.2                | #929
     | pypi       | mleap               | 0.8.1                | #930
     | pypi       | javaobj-py3         | 0.3.0                | #931
     | pypi       | warlock             | 1.3.3                | #932
     | pypi       | requests-ntlm       | 1.1.0                | #933
     | pypi       | pre-commit          | 1.18.0               | #935
     | pypi       | flask-cache         | 0.13.1               | #936
     | pypi       | rasterio            | 1.0.25               | #937
     | pypi       | pyjks               | 19.0.0               | #938
     | pypi       | distribute          | 0.7.3                | #939
     | pypi       | twofish             | 0.3.0                | #940
     | pypi       | lz4                 | 2.1.10               | #941
     | pypi       | mrjob               | 0.6.10               | #942
     | pypi       | readme-renderer     | 24.0                 | #943
     | pypi       | python-openstackclient | 3.19.0               | #944
     | pypi       | cfn-flip            | 1.2.1                | #945
     | pypi       | python-gnupg        | 0.4.4                | #946
     | pypi       | livereload          | 2.6.1                | #947
     | pypi       | txaio               | 18.8.1               | #948
     | pypi       | azure-eventgrid     | 1.3.0                | #949
     | pypi       | recommonmark        | 0.5.0                | #950
     | pypi       | ciso8601            | 2.1.1                | #951
     | pypi       | troposphere         | 2.5.0                | #952
     | pypi       | azure-storage-file  | 2.1.0                | #953
     | pypi       | sqlalchemy-migrate  | 0.12.0               | #954
     | pypi       | nose-timer          | 0.7.5                | #955
     | pypi       | pep8-naming         | 0.8.2                | #956
     | pypi       | connexion           | 2.3.0                | #957
     | pypi       | plumbum             | 1.6.7                | #958
     | pypi       | falcon              | 2.0.0                | #959
     | pypi       | ddtrace             | 0.27.1               | #960
     | pypi       | clickclick          | 1.2.2                | #961
     | pypi       | flake8-docstrings   | 1.3.1                | #962
     | pypi       | pyvcf               | 0.6.8                | #963
     | pypi       | cssselect2          | 0.2.1                | #964
     | pypi       | virtualenvwrapper   | 4.8.4                | #965
     | pypi       | logging             | 0.4.9.6              | #966
     | pypi       | mozinfo             | 1.1.0                | #967
     | pypi       | comtypes            | 1.1.7                | #968
     | pypi       | ntlm-auth           | 1.3.0                | #970
     | pypi       | azure-mgmt-applicationinsights | 0.2.0                | #971
     | pypi       | mozrunner           | 7.5.0                | #972
     | pypi       | querystring-parser  | 1.2.4                | #973
     | pypi       | pyqt5               | 5.13.0               | #974
     | pypi       | pytimeparse         | 1.1.8                | #975
     | pypi       | mozfile             | 2.0.0                | #976
     | pypi       | gapic-google-cloud-pubsub-v1 | 0.15.4               | #977
     | pypi       | flaky               | 3.6.1                | #978
     | pypi       | diff-match-patch    | 20181111             | #979
     | pypi       | webapp2             | 2.5.2                | #980
     | pypi       | proto-google-cloud-pubsub-v1 | 0.15.4               | #981
     | pypi       | django-ipware       | 2.1.0                | #982
     | pypi       | identify            | 1.4.5                | #983
     | pypi       | timeout-decorator   | 0.4.1                | #984
     | pypi       | pyinstaller         | 3.5                  | #985
     | pypi       | mpi4py              | 3.0.2                | #986
     | pypi       | graphene            | 2.1.7                | #987
     | pypi       | social-auth-core    | 3.2.0                | #988
     | pypi       | ipaddr              | 2.2.0                | #989
     | pypi       | oauth2              | 1.9.0.post1          | #990
     | pypi       | googledatastore     | 7.1.0                | #991
     | pypi       | setupmeta           | 2.6.5                | #992
     | pypi       | defer               | 1.0.4                | #993
     | pypi       | weasyprint          | 48                   | #995
     | pypi       | spark-sklearn       | 0.3.0                | #996
     | pypi       | argon2-cffi         | 19.1.0               | #997
     | pypi       | mozterm             | 1.0.0                | #998
     | pypi       | azure-mgmt-datafactory | 0.7.0                | #999
