---
apiVersion: v1
kind: Template
metadata:
  name: bayesian-secrets-template
apiVersion: v1
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: coreapi-postgres
  type: Opaque
  data:
    database: Y29yZWFwaQ==  # coreapi
    initial-database: cG9zdGdyZXM=  # postgres
    port: NTQzMg==  # 5432
    username: Y29yZWFwaQ==  # coreapi
    host: ${RDS_ENDPOINT}
    password: ${RDS_PASSWORD}
- apiVersion: v1
  kind: Secret
  metadata:
    name: anitya-postgres
  type: Opaque
  data:
    database: YW5pdHlh  # anitya
    initial-database: cG9zdGdyZXM=  # postgres
    port: NTQzMg==  # 5432
    username: Y29yZWFwaQ==  # coreapi
    host: ${RDS_ENDPOINT}
    password: ${RDS_PASSWORD}
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws
  type: Opaque
  data:
    dynamodb-access-key-id: ${AWS_ACCESS_KEY_ID}
    dynamodb-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    emr-access-key-id: ${AWS_ACCESS_KEY_ID}
    emr-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    s3-access-key-id: ${AWS_ACCESS_KEY_ID}
    s3-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    sqs-access-key-id: ${AWS_ACCESS_KEY_ID}
    sqs-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    sync-s3: MQ==  # 1
- apiVersion: v1
  kind: Secret
  metadata:
    name: 3scale
  type: Opaque
  data:
    three_scale_api_access_key : ${THREE_SCALE_API_ACCESS_KEY}
    three_scale_api_account_id : ${THREE_SCALE_API_ACCOUNT_ID}
- apiVersion: v1
  kind: Secret
  metadata:
    name: 3scale-apicast-gateway
  type: Opaque
  data:
    password : ${THREESCALE_PORTAL_ENDPOINT}
- apiVersion: v1
  kind: Secret
  metadata:
    name: worker
  type: Opaque
  data:
    blackduck-host: ZXhhbXBsZS5jb20=  # example.com
    blackduck-password: cGFzc3dvcmQ=  # password
    blackduck-path: L29wdC9ibGFja2R1Y2sv  # /opt/blackduck/
    blackduck-port: ODA4MA==  # 8080
    blackduck-scheme: aHR0cA==  # http
    blackduck-username: dXNlcm5hbWU=  # username
    github-token: ${GITHUB_API_TOKENS}
    pulp-password: bm90LXNldA==  # not-set
    pulp-url: ZXhhbXBsZS5jb20=  # example.com
    pulp-username: bm90LXNldA==  # not-set
- apiVersion: v1
  kind: Secret
  metadata:
    name: jobs
  type: Opaque
  data:
    github-oauth-consumer-key: ${GITHUB_OAUTH_CONSUMER_KEY}
    github-oauth-consumer-secret: ${GITHUB_OAUTH_CONSUMER_SECRET}
    flask-app-secret-key: ${FLASK_APP_SECRET_KEY}
- apiVersion: v1
  kind: Secret
  metadata:
    name: google-cloud-key
  type: Opaque
  data:
    gcp_type:
    gcp_project_id:
    gcp_private_key_id:
    gcp_private_key:
    gcp_client_email:
    gcp_client_id:
    gcp_auth_uri:
    gcp_token_uri:
    gcp_auth_provider_x509_cert_url:
    gcp_client_x509_cert_url:

parameters:
- description: AWS access key
  displayName: AWS_ACCESS_KEY_ID
  required: true
  name: AWS_ACCESS_KEY_ID

- description: AWS secret key
  displayName: AWS_SECRET_ACCESS_KEY
  required: true
  name: AWS_SECRET_ACCESS_KEY

- description: A comma-separated list of GitHub API tokens
  displayName: GITHUB_API_TOKENS
  required: true
  name: GITHUB_API_TOKENS
  value: "bm90LXNldA=="  # not-set

- description: GitHub OAuth consumer key
  displayName: GitHub OAuth consumer key
  required: true
  name: GITHUB_OAUTH_CONSUMER_KEY
  value: "bm90LXNldA=="  # not-set

- description: GitHub OAuth consumer secret
  displayName: GitHub OAuth consumer secret
  required: true
  name: GITHUB_OAUTH_CONSUMER_SECRET
  value: "bm90LXNldA=="  # not-set

- description: Flask App secret key
  displayName: Flask App secret key
  required: true
  name: FLASK_APP_SECRET_KEY
  value: "bm90LXNldA=="  # not-set

- description: RDS endpoint
  displayName: RDS endpoint
  required: true
  name: RDS_ENDPOINT
  value: "bm90LXNldA=="  # not-set

- description: RDS password
  displayName: RDS password
  required: true
  name: RDS_PASSWORD
  value: "bm90LXNldA=="  # not-set

- description: 3scale API access key
  displayName: 3scale API access key
  required: true
  name: THREE_SCALE_API_ACCESS_KEY
  value: "bm90LXNldA=="  # not-set

- description: 3scale API account ID
  displayName: 3scale API account ID
  required: true
  name: THREE_SCALE_API_ACCOUNT_ID
  value: "bm90LXNldA=="  # not-set

- description: Name of the secret containing the THREESCALE_PORTAL_ENDPOINT with the access-token or provider key
  displayName: 3scale apicast portal endpoint
  required: true
  name: THREESCALE_PORTAL_ENDPOINT
  value: "bm90LXNldA=="  # not-set
