apiVersion: v1
kind: Template
metadata:
  name: bayesian-secrets-template
apiVersion: v1
objects:
- apiVersion: v1
  data:
    database:
    host:
    initial-database:
    password:
    port:
    username:
  kind: Secret
  metadata:
    name: anitya-postgres
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws
  type: Opaque
  data:
    dynamodb-access-key-id:
    dynamodb-secret-access-key:
    emr-access-key-id:
    emr-secret-access-key:
    s3-access-key-id:
    s3-secret-access-key:
    sqs-access-key-id:
    sqs-secret-access-key:
    sync-s3:
- apiVersion: v1
  kind: Secret
  metadata:
    name: coreapi-postgres
  type: Opaque
  data:
    database:
    host:
    initial-database:
    password:
    port:
    username:
- apiVersion: v1
  kind: Secret
  metadata:
    name: worker
  type: Opaque
  data:
    blackduck-host: ZXhhbXBsZS5jb20=  # example.com
    blackduck-password: cGFzc3dvcmQ=  # password
    blackduck-path: L29wdC9ibGFja2R1Y2sv  # /opt/blackduck/
    blackduck-port: ODA4MA==  # 8080
    blackduck-scheme: aHR0cA==  # http
    blackduck-username: dXNlcm5hbWU=  # username
    github-token:
    pulp-password:
    pulp-url:
    pulp-username:
- apiVersion: v1
  kind: Secret
  metadata:
    name: jobs
  type: Opaque
  data:
    github-oauth-consumer-key:
    github-oauth-consumer-secret:
    flask-app-secret-key:
- apiVersion: v1
  kind: Secret
  metadata:
    name: google-cloud-key
  type: Opaque
  data:
    gcp_type:
    gcp_project_id:
    gcp_private_key_id:
    gcp_private_key:
    gcp_client_email:
    gcp_client_id:
    gcp_auth_uri:
    gcp_token_uri:
    gcp_auth_provider_x509_cert_url:
    gcp_client_x509_cert_url:
